name:  Ci/ Cd springboot-demo

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ['self-hosted', 'Linux', 'extension' ]

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    
    # - name: stop old docker compose
    #   run: sudo docker-compose down || true

    - name: Build with Maven
      run: mvn -B package --file pom.xml
